apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: psynapse

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: app-env
    envs:
      - .env.k8s
    type: Opaque
